### ISSUE TITLE
specific protein counts

### ISSUE THREAD

**Issue by happy-lorna** [ProteinsWebTeam/interpro7-client#123]
Is there a way to get the specific number of proteins matched by an entry? For IPR023897 I can see it matches 2K proteins, but is there a way to find the specific number of matches?

**Comment by matthiasblum** [comment]
It is possible using the API: [/api/entry/InterPro/IPR023897/](http://www.ebi.ac.uk/interpro/beta/api/entry/InterPro/IPR023897/) returns a JSON objects with a `counters` property.

**Comment by gustavo-salazar** [comment]
@matthiasblum is correct that you can get the precise number from there.

But this is one of the few cases where we are sure of that number, because those values there are precalculated. This is not the case in most of the website. To calculate most of the values on the fly we are heavy users of aggregations in elasticsearch (one of our data storage technology). 
And as you can see [HERE](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate) aggregation counts are approximated. Which is a sacrifice we have made in order to be able to deliver the required speed of a modern website.

Therefore we have decided to show approximated values almost everywhere in the website.

**Comment by happy-lorna** [comment]
Thanks for the explanation. Presumably accurate values are calculated up until a certain number, is that correct? If so, what is the maximum value that an accurate count exists for in the website?

**Comment by gustavo-salazar** [comment]
It is hard to put an exact number there... is most like the probability of errors is smaller.
The default threshold is 3000, and I think we are using the default value, isn't @matthiasblum ?

TBH, most of the times the values are correct even in the order of millions. 

The basic problem is that we have our data split among multiple machines(AKA shards) and when doing any sort of aggregation, such as counting the *unique* proteins that are matched by an entry, the calculations get done on every shard, and then there is a process to unify these partial results, and that step is not exact.
