### ISSUE TITLE
UniProt accessions with no match to InterPro

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#139]
In the old site, it admits that the protein exists, but with no matches:

https://www.ebi.ac.uk/interpro/protein/Q9Y6Z5

In the new site:

https://www.ebi.ac.uk/interpro/beta/search/text/Q9Y6Z5

Should the response be the same - i.e. "no matches" rather than "doesn't exist"? One for curation team etc. Might be helpful if the API also says that there are no matches:

https://www.ebi.ac.uk/interpro/beta/api/protein/UniProt/entry/InterPro/taxonomy/uniprot/9606?search=Q9Y6Z5

**Comment by gustavo-salazar** [comment]
The protein is actually there: 
* website: https://www.ebi.ac.uk/interpro/beta/protein/UniProt/Q9Y6Z5/
* api: https://www.ebi.ac.uk/interpro/beta/api/protein/UniProt/Q9Y6Z5/
The problem is that is not indexed in the ebisearch because everything in the index is from the point of view of entries, and because that protein doesn't have matches then it got ignored.

I'll be searching a way to include them in the result page.

**Comment by matthiasblum** [comment]
When no results are returned (e.g. because the protein or structure isn't hit by any entry), we could check if the search string (e.g. _Q9Y6Z5_) is a valid UniProt accession using either the MySQL database or EBI Search (UniProt domain: [www.ebi.ac.uk/ebisearch/ws/rest/uniprot/entry/Q9Y6Z5](http://www.ebi.ac.uk/ebisearch/ws/rest/uniprot/entry/Q9Y6Z5)).
