### ISSUE TITLE
Filtering taxa by taxon ID

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#45]
When browsing the [taxa](http://www.ebi.ac.uk/interpro/beta/taxonomy/uniprot/entry/InterPro/), we can use the text search box to filter results. It works as expected when searching for a string (e.g. _Homo sapiens_) but not when searching by taxon ID (e.g. _9606_): partial hits (e.g. taxa with IDs such as _1019606_ or _1196063_) are returned as well. One could expect to have only the searched taxon ID returned, or at least to have this taxon placed first in the table.

(I guess this applies to the API as well)

**Comment by 4ndr01d3** [comment]
Yeah, this had more to do with the API.
What happened is that the text quey I was sending to elastic was something like `*9606*`, which then created the issue of including other matches that weren't so exact.
Moreover, that kind of query was slowing down the search, because it didn't take advantage of the tokenizers in elastic. 
I have change the API so the query doesn't include the wildcards, given more exact matches and taking less time.
However this have a caveat. Now the results won't include the cases you described, which in tax ids is not such an issue, but in normal text can have a repercussion on composed words. For example it won't find `"alphanumerical"` if the search term is `"alpha"`.

PS. the change is live, but some of the search are in redis. I'll try to delete that from the cache.
