### ISSUE TITLE
Deactivate scroll-to-zoom on entry > protein page

### ISSUE THREAD

**Issue by aurel-l** [ProteinsWebTeam/interpro7-client#50]
The protvista components on the table view of the entry page, protein subpage are zooming in and out when scrolling over them.
Since there is no coordinates displayed, it doesn't make sense to the user and should be disabled.

example: [https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR000001/protein/UniProt/#table](https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR000001/protein/UniProt/#table) domain architecture column

**Comment by 4ndr01d3** [comment]
I did some optimisations in protvista sequence, which might be enough to included here without major performance issues. But I'm waiting for a chage that xavier wanted to include before re-publishing protvista... 
I'll give it a try and re enable the sequence size view, or disable the zoom completely

**Comment by 4ndr01d3** [comment]
Zoom has been disable, as wasn't bringing anything new to the page, we are now including a tooltip to show the coordinates of the entry in the sequence. 
The sequence component was added back, as it won't affect so much the performance, because it is not drawing invisible characters.
Now in `dev` branch`
