### ISSUE TITLE
Loading page issue - first time user

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#58]
It seems that there is still a loading issue on the homepage, just the first time we try to access it , it just shows the loading 3 dots in loop (tried from EBI remote desktop on Chrome, IE, and Firefox: same result). When refreshing the page, then it works.

**Comment by gustavo-salazar** [comment]
The issue is that for some reason the first JS file is not loaded.
The implemented workaround for this, is to give 30sec to the first module to be loaded, if everything is OK,  the main div should be included to the DOM. But if it hasn't the whole page will be reloaded.
The 30 sec time was chosen as it should be enough time to load the first file ~600KB in an slow 3G connection.
